config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "authors#index"

  resources :authors, :articles, :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :author
    has_and_belongs_to_many :tags
    has_many :comments
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    def show
        @article = Article.find(params[:id])
        @author = Author.find(params[:authorId]).name
        @tags = @article.tags.all
    end
    
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :set_page, only: [:index, :show]
    # before_action :set_article_page, only: [:index]
    def index
        @authors = Author.all
        @authorsOrder = Author.order(created_at: :desc).limit(6).offset(@page.to_i * 6)
    end
    def show
        @author = Author.find(params[:id])
        @articles = @author.articles.all
        @articlesOrder = @author.articles.order(created_at: :desc).limit(6).offset(@page.to_i * 6)
    end

    private

    def set_page
        @page = params[:page] || 0
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def show
        @tag = Tag.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/index.html.haml
%h1 All available articles 
-@articles.each do |article|
    %p=link_to article.title, article_path(article, authorId: article.author_id)

app/views/articles/show.html.haml
%h1 Article name: #{@article.title}
%h3 Author: #{@author}
%h4 tags:
-@tags.each do |tag|
    %span
    =link_to tag.name, tag_path(tag)

app/views/authors/index.html.haml
%h1 All Authors
%ul
    -@authorsOrder.each do |author|
        %li
            =link_to author.name, author_path(author)
-for i in 0..@authors.length/6 do 
    =link_to (i + 1), authors_path(page: i)

app/views/authors/show.html.haml
%h1=@author.name
%h3 email: #{@author.email}
%h3 city: #{@author.city}
%h3 adress: #{@author.adress}
%h3 birthday: #{@author.birthDate.strftime('%d-%m-%Y')}
-@articlesOrder.each do |article|
    %h4    
        %li
            =link_to article.title, article_path(article, authorId: article.author_id)
            %span tags:
            -article.tags.each do |tag|
                =link_to tag.name, tag_path(tag)

-for i in 0..@articles.length/6 do 
    =link_to (i + 1), author_path(@author, page: i)

            

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GistApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %nav
      =link_to "All authors", root_path
      =link_to "All artisles", articles_path
    %main
      = yield

app/views/tags/show.html.haml
%h1 Articles with tag: #{@tag.name}
-@tag.articles.each do |article|
    %p=link_to article.title, article_path(article, authorId: article.author_id)